# Generated by Django 4.1.4 on 2023-03-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(max_length=50)),
                ('Payment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=150)),
                ('Date', models.DateTimeField()),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Tags', models.CharField(max_length=200)),
                ('Nbr_Rating', models.IntegerField()),
                ('Rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('PassWord', models.CharField(max_length=100)),
                ('CartHolder', models.CharField(max_length=100)),
                ('Criditcart', models.IntegerField()),
                ('Expiration', models.DateField()),
                ('CVV', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manpro.user')),
                ('Profession', models.CharField(max_length=50)),
                ('Education_Level', models.CharField(max_length=50)),
                ('Nbr_Rating', models.IntegerField()),
                ('Rating', models.FloatField()),
            ],
            bases=('manpro.user',),
        ),
        migrations.CreateModel(
            name='ProjectRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Rating', models.IntegerField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.jobs')),
                ('Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Languge', models.CharField(max_length=50)),
                ('IS_Finished', models.BooleanField()),
                ('Date_Start', models.DateField()),
                ('Duration', models.DateField()),
                ('Budget', models.FloatField()),
                ('LinkF', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=500)),
                ('Manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manpro.user')),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manpro.team')),
            ],
        ),
        migrations.CreateModel(
            name='NotifUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_read', models.BooleanField()),
                ('Notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.notification')),
                ('UserNot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.user')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manpro.user'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=200)),
                ('DateT', models.DateTimeField()),
                ('By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manpro.user')),
                ('Conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='LinksPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=150)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.post')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.project'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=150)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.post')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.user')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='User1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User1', to='manpro.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='User2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User2', to='manpro.user'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=200)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerMetrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Rating', models.IntegerField()),
                ('Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.skill')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Work_For',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=50)),
                ('payment', models.FloatField()),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.team')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.worker')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.worker'),
        ),
        migrations.CreateModel(
            name='LinksProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=150)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.worker')),
            ],
        ),
    ]
