# Generated by Django 4.1.4 on 2023-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0004_user_profilephoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkerMetrise',
            new_name='workerMaitrise',
        ),
        migrations.AddField(
            model_name='worker',
            name='Bio',
            field=models.CharField(default='', max_length=201),
        ),
    ]
