# Generated by Django 4.1.4 on 2023-03-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0012_remove_work_for_job_remove_work_for_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_For',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Apply', models.DateField()),
                ('Job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manpro.jobs')),
                ('Worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manpro.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Work_For',
            fields=[
                ('apply_for_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manpro.apply_for')),
                ('Date_Work', models.DateField()),
            ],
            bases=('manpro.apply_for',),
        ),
    ]
