# Generated by Django 4.1.4 on 2023-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0015_apply_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_for',
            name='Date_Work',
            field=models.DateField(null=True),
        ),
    ]
