# Generated by Django 4.1.4 on 2023-04-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0017_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='Description',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='worker',
            name='Avalble',
            field=models.BooleanField(default=True),
        ),
    ]
