# Generated by Django 4.1.4 on 2023-04-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0019_alter_apply_for_date_apply_alter_apply_for_date_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Description',
            field=models.CharField(default='_', max_length=300),
        ),
        migrations.CreateModel(
            name='RateWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rater', to='manpro.worker')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker', to='manpro.user')),
            ],
        ),
    ]
