# Generated by Django 4.1.4 on 2023-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0023_search_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
