# Generated by Django 4.1.4 on 2023-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0025_interestedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedjobs',
            name='Is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
