# Generated by Django 4.1.4 on 2023-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0026_interestedjobs_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='LinkChat',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
