# Generated by Django 4.1.4 on 2023-05-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0028_alter_project_budget_alter_project_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Budget',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='LinkChat',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='LinkF',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
