# Generated by Django 4.1.4 on 2023-08-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0029_alter_project_budget_alter_project_linkchat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Tags',
        ),
        migrations.AddField(
            model_name='post',
            name='Categorie',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='Logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Type',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='URL',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='LinkChat',
            field=models.CharField(default='\\', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='LinkF',
            field=models.CharField(default='\\', max_length=150),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.user')),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=500)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.post')),
            ],
        ),
    ]
