# Generated by Django 4.1.4 on 2023-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0030_remove_post_tags_post_categorie_post_logo_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePhoto',
            field=models.ImageField(default='anonymous.png', upload_to=''),
        ),
    ]
