# Generated by Django 4.1.4 on 2023-08-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0031_alter_user_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CVV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='CartHolder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Criditcart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfilePhoto',
            field=models.ImageField(default='anonymous.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cardMonth',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cardYear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
