# Generated by Django 4.1.4 on 2023-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0033_remove_user_is_worker_user_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateworker',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
