# Generated by Django 4.1.4 on 2023-09-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0034_alter_rateworker_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateworker',
            name='Rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
