# Generated by Django 4.1.4 on 2023-09-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0036_alter_user_cardmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Special',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
