# Generated by Django 4.1.4 on 2023-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0037_post_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Prix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
