# Generated by Django 4.1.4 on 2023-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0039_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historypost',
            name='Save',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='AgeAuto',
            field=models.CharField(blank=True, default='+3', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='DateRelease',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='DateUpdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Finiched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Forseal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='TeamName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='Version',
            field=models.CharField(blank=True, default='1', max_length=20),
        ),
    ]
