# Generated by Django 4.1.4 on 2023-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0042_historypost_content_historypost_date_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='Contant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='Email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='PlusCnt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offers',
            name='Prix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
