# Generated by Django 4.1.4 on 2023-10-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0043_offers_contant_offers_email_offers_pluscnt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=500)),
                ('State', models.CharField(max_length=50)),
                ('Prix', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.user')),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.offers')),
            ],
        ),
    ]
