# Generated by Django 4.1.4 on 2023-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0045_rename_contant_offers_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_offer',
            name='Num_Tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
