# Generated by Django 4.1.4 on 2023-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0046_user_offer_num_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_offer',
            old_name='Prix',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='user_offer',
            name='State',
            field=models.CharField(max_length=20),
        ),
    ]
