# Generated by Django 4.1.4 on 2023-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0003_user_is_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ProfilePhoto',
            field=models.CharField(default='anonymous.png', max_length=50),
        ),
    ]
