# Generated by Django 4.1.4 on 2023-03-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0007_worker_nbr_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Team',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='projectrequired',
            old_name='Project',
            new_name='Job',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='work_for',
            name='Team',
        ),
        migrations.AddField(
            model_name='project',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='work_for',
            name='Project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manpro.project'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
