# Generated by Django 4.1.4 on 2023-03-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0008_rename_team_jobs_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Languge',
        ),
    ]
