# Generated by Django 4.1.4 on 2023-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0009_remove_project_languge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Payment',
            field=models.CharField(max_length=50),
        ),
    ]
