# Generated by Django 4.1.4 on 2023-03-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0010_alter_jobs_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_For',
            fields=[
                ('work_for_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manpro.work_for')),
                ('Date', models.DateField()),
            ],
            bases=('manpro.work_for',),
        ),
        migrations.RemoveField(
            model_name='project',
            name='IS_Finished',
        ),
        migrations.RemoveField(
            model_name='work_for',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='work_for',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='work_for',
            name='payment',
        ),
        migrations.AddField(
            model_name='jobs',
            name='State',
            field=models.CharField(default='_', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='State',
            field=models.CharField(default='_', max_length=50),
        ),
        migrations.AddField(
            model_name='work_for',
            name='Job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manpro.jobs'),
        ),
    ]
