# Generated by Django 4.1.4 on 2023-04-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0014_remove_work_for_apply_for_ptr_delete_apply_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_For',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Apply', models.DateField()),
                ('Date_Work', models.DateField()),
                ('State', models.BooleanField(default=False)),
                ('Job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manpro.jobs')),
                ('Worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manpro.worker')),
            ],
        ),
    ]
