# Generated by Django 4.1.4 on 2023-04-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0016_alter_apply_for_date_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Link',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
