# Generated by Django 4.1.4 on 2023-04-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0020_alter_jobs_description_rateworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateworker',
            name='Rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rater', to='manpro.user'),
        ),
        migrations.AlterField(
            model_name='rateworker',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker', to='manpro.worker'),
        ),
    ]
