# Generated by Django 4.1.4 on 2023-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0022_alter_user_email_alter_user_username_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
