# Generated by Django 4.1.4 on 2023-04-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0024_search_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viewcount', models.IntegerField(default=1)),
                ('Time', models.DateTimeField(null=True)),
                ('Save', models.BooleanField(default=False)),
                ('Apply', models.BooleanField(default=False)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.jobs')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpro.worker')),
            ],
        ),
    ]
