# Generated by Django 4.1.4 on 2023-05-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpro', '0027_project_linkchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='Date_Start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Duration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='LinkChat',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='LinkF',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
